services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: coffee-mock-api-server
    ports:
      - "5001:3001"
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - coffee-net

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: coffee-admin-web-client
    ports:
      - "5000:3000"
    volumes:
      - ./client:/app
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    command: sh -c "npm install && npm run dev"
    depends_on:
      - server
    networks:
      - coffee-net

networks:
  coffee-net:
    driver: bridge
